name: Security Scan

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: Checkov Security Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: charts/
          framework: kubernetes,helm
          output_format: cli
          quiet: false
          soft_fail: true
          
      - name: Display Checkov results
        run: |
          echo "Checkov scan completed. Check the logs above for any security findings."
          echo "Note: This is set to soft_fail, so the workflow will continue even with findings."

  trivy:
    runs-on: ubuntu-latest
    name: Trivy Configuration Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'charts/'
          format: 'table'
          exit-code: '0'  # Don't fail the workflow

  polaris:
    runs-on: ubuntu-latest
    name: Polaris Configuration Validation
    continue-on-error: true  # Don't fail the workflow if Polaris finds issues
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install Polaris
        run: |
          curl -L https://github.com/FairwindsOps/polaris/releases/latest/download/polaris_linux_amd64.tar.gz \
            | tar -xz polaris
          sudo mv polaris /usr/local/bin/

      - name: Run Polaris audit
        run: |
          for chart_dir in charts/*/; do
            if [[ -d "$chart_dir" ]]; then
              chart_name=$(basename "$chart_dir")
              echo "🔍 Running Polaris audit for $chart_name..."
              
              # Render chart and audit with Polaris
              helm template test-release "$chart_dir" | \
                polaris audit --audit-path - \
                --format pretty \
                --only-show-failed-tests false || true
            fi
          done